### ISSUE TITLE
Can't pair my smartwatches (Fold4,Watch3,GearS2)

### ISSUE THREAD

**Issue by Conan179** [adil192/SamsungAppsPatcher#12]
Hi, I can't get it working with the patched apks. I can't connect my two smart watches (Watch3 and the Gear S2) with it. When I try to connect to my Fold4 (rooted), both watch plugins have force closed and won't connect. I hope I can get help for my problem here.

**Comment by adil192** [comment]
Please can you provide the following information...
- What's your Android/OneUI version?
- Which apks have you installed and what are their versions?
- Have you tried running `wearable-wipe.sh`?

(Please bear in mind that this project is unmaintained and can't really be developed any further by me)

**Comment by Conan179** [comment]
Yes, of course :)

- Android 12 One UI 4.1.1
- Galaxy Wearable 21 July 2022, Accessory Service, 11 August 2022, Galaxy Watch3 Plugin 15 July 2022, Galaxy Watch3 Plugin 15 July 2022 all from https://adil.hanney.org/SamsungAppsPatcher/
- Oh no, I haven't tried the script yet, I'll try that right away.

I know.

**Comment by adil192** [comment]
> ```
> /storage/emulated/0/wearable-wipe.sh[52]: adb: inaccessible or not found
> ```

Ah, the script was intended to be run on a computer.
If you want to run it directly on Android (I haven't tried it), you can edit the script and remove the `adb shell` prefix, e.g. change `adb shell pm uninstall "$app"` to `pm uninstall "$app"`

**Comment by Conan179** [comment]
I noticed too late that you have to run the script on a Linux pc, sorry. I couldn't get a Linux installation on the fly. I'll try it right away.

**Comment by adil192** [comment]
> ok, after the script I installed these 3 apps: Galaxy Wearable 21 July 2022, Accessory Service, 11 August 2022, Gear S Plugin 2 May 2022 then I get this error message: 

Please can you run a logcat with this command `adb logcat -b crash` (I think you could need a computer for this step, otherwise try `logcat -b crash` on your phone) and then open Wearable to see the crash, then send the logcat here

**Comment by Conan179** [comment]
No problem:

`08-24 00:02:55.413 25609 25609 E AndroidRuntime: FATAL EXCEPTION: main
08-24 00:02:55.413 25609 25609 E AndroidRuntime: Process: com.samsung.android.gearoplugin, PID: 25609
08-24 00:02:55.413 25609 25609 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.samsung.android.hostmanager.connectionmanager.ConnectionManager: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10524 nor current process has com.sec.permission.BLUETOOTH_DEBUG.
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5156)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.app.ActivityThread.access$2000(ActivityThread.java:324)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2355)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8855)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
08-24 00:02:55.413 25609 25609 E AndroidRuntime: Caused by: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10524 nor current process has com.sec.permission.BLUETOOTH_DEBUG.
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2421)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2404)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2346)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.bluetooth.IBluetooth$Stub$Proxy.configHciSnoopLogForExternal(IBluetooth.java:8370)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.bluetooth.BluetoothAdapter.semConfigHciSnoopLogForExternal(BluetoothAdapter.java:6874)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at com.samsung.android.app.watchmanager.plugin.selibrary.bluetooth.BluetoothAdapterManager.configHciSnoopLogForExternal(BluetoothAdapterManager.java:24)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.util.BluetoothUtil.configHciSnoopLogForExternal(BluetoothUtil.java:352)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.eventhandler.EventHandler.<init>(EventHandler.java:88)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.ConnectionManager.initialize(ConnectionManager.java:340)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.ConnectionManager.startConnectionManager(ConnectionManager.java:271)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.ConnectionManager.onCreate(ConnectionManager.java:188)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5143)
08-24 00:02:55.413 25609 25609 E AndroidRuntime:        ... 9 more
08-24 00:02:59.724 25809 25809 E AndroidRuntime: FATAL EXCEPTION: main
08-24 00:02:59.724 25809 25809 E AndroidRuntime: Process: com.samsung.android.gearoplugin, PID: 25809
08-24 00:02:59.724 25809 25809 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.samsung.android.hostmanager.connectionmanager.ConnectionManager: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10524 nor current process has com.sec.permission.BLUETOOTH_DEBUG.
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5156)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.app.ActivityThread.access$2000(ActivityThread.java:324)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2355)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8855)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
08-24 00:02:59.724 25809 25809 E AndroidRuntime: Caused by: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10524 nor current process has com.sec.permission.BLUETOOTH_DEBUG.
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2421)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2404)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2346)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.bluetooth.IBluetooth$Stub$Proxy.configHciSnoopLogForExternal(IBluetooth.java:8370)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.bluetooth.BluetoothAdapter.semConfigHciSnoopLogForExternal(BluetoothAdapter.java:6874)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at com.samsung.android.app.watchmanager.plugin.selibrary.bluetooth.BluetoothAdapterManager.configHciSnoopLogForExternal(BluetoothAdapterManager.java:24)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.util.BluetoothUtil.configHciSnoopLogForExternal(BluetoothUtil.java:352)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.eventhandler.EventHandler.<init>(EventHandler.java:88)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.ConnectionManager.initialize(ConnectionManager.java:340)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.ConnectionManager.startConnectionManager(ConnectionManager.java:271)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at com.samsung.android.hostmanager.connectionmanager.ConnectionManager.onCreate(ConnectionManager.java:188)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5143)
08-24 00:02:59.724 25809 25809 E AndroidRuntime:        ... 9 more`

**Comment by adil192** [comment]
> ```python
> java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10524 nor current process has com.sec.permission.BLUETOOTH_DEBUG.
> ```

Are there any bluetooth-related permissions that aren't enabled on either Gear S Plugin or Wearable?

**Comment by Conan179** [comment]
I'm sorry, but I know enough about the internal androids to answer your question.

Witch gearsplugin-issue-12.apk I get the same error message on my foold4 and this is in the logcat:

`08-24 09:17:53.325  9739  9739 E AndroidRuntime: FATAL EXCEPTION: main
08-24 09:17:53.325  9739  9739 E AndroidRuntime: Process: com.samsung.android.gearoplugin, PID: 9739
08-24 09:17:53.325  9739  9739 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.notsamsung.dummy: java.lang.ClassNotFoundException: Didn't find class "com.notsamsung.dummy" on path: DexPathList[[zip file "/data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/lib/arm64, /data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5156)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at android.app.ActivityThread.access$2000(ActivityThread.java:324)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2355)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8855)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
08-24 09:17:53.325  9739  9739 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.notsamsung.dummy" on path: DexPathList[[zip file "/data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/lib/arm64, /data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5125)
08-24 09:17:53.325  9739  9739 E AndroidRuntime:        ... 9 more
08-24 09:18:03.456  9958  9958 E AndroidRuntime: FATAL EXCEPTION: main
08-24 09:18:03.456  9958  9958 E AndroidRuntime: Process: com.samsung.android.gearoplugin, PID: 9958
08-24 09:18:03.456  9958  9958 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.notsamsung.dummy: java.lang.ClassNotFoundException: Didn't find class "com.notsamsung.dummy" on path: DexPathList[[zip file "/data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/lib/arm64, /data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5156)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at android.app.ActivityThread.access$2000(ActivityThread.java:324)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2355)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8855)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
08-24 09:18:03.456  9958  9958 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.notsamsung.dummy" on path: DexPathList[[zip file "/data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/lib/arm64, /data/app/~~ZUh8GpZ_0KGmxx2pmgzaPA==/com.samsung.android.gearoplugin-Eb_rKa0fwv-uKlzEf0B_zw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:5125)
08-24 09:18:03.456  9958  9958 E AndroidRuntime:        ... 9 more`

**Comment by adil192** [comment]
> ```python
> java.lang.ClassNotFoundException: Didn't find class "com.notsamsung.dummy"
> ```

Reinstall the normal gearsplugin for now

> I'm sorry, but I know enough about the internal androids to answer your question.

Go to Settings, Apps, Gear S Plugin, Permissions, and enable all the permissions. Do the same for Wearable and then send another log 
Thanks

**Comment by Conan179** [comment]
The  new installation only of gearsplugin does not work, this error message appears:
![2022-08-24 14 28 06 - Kopie](https://user-images.githubusercontent.com/1906242/186418801-e0843334-aeef-4370-b695-a9575d324c15.jpg)

**Comment by adil192** [comment]
> ![2022-08-24 14 28 06 - Kopie](https://user-images.githubusercontent.com/1906242/186418801-e0843334-aeef-4370-b695-a9575d324c15.jpg)

Please can you translate this to English?

**Comment by Conan179** [comment]
No Problem
![2022-08-24 14 50 05](https://user-images.githubusercontent.com/1906242/186422809-01ce1324-7a1e-41b3-8a8f-addc11e9d28b.jpg)

**Comment by adil192** [comment]
is that with the unmodded apk? I probably should have been more clear; I meant the normal modded apk from the project website

**Comment by Conan179** [comment]
I already thought so ;) so first I only uninstalled the gearsplugin, when that didn't work I deleted all wearable apps via wipe script and only installed the Samsung wearable app from the site.  Both times the same error message.

**Comment by Conan179** [comment]
by the way, the Galaxy Buds Live Manager 16 May 2022 patch from the site are 100% working.

**Comment by adil192** [comment]
did that same gearsplugin apk work for you before?

**Comment by Conan179** [comment]
I think I should break it down now:
1. With the Galaxy Wearable from the playstore I don't have a force close, it remains hanging when setting up, both watches.
2. If I install Galaxy Wearable, Accessory Service and gearsplugin as apk from the side, I get a force close when setting up.
3. With the Galaxy Wearable apk from the side, and let it install Accessory Service and gearsplugin by itself, the message "package conflicts" comes up.

**Comment by adil192** [comment]
> 3. With the Galaxy Wearable apk from the side, and let it install Accessory Service and gearsplugin by itself, the message "package conflicts" comes up.

Ah, that makes more sense. Wearable will try to install the official Samsung apks not the modded ones, hence the conflict

**Comment by Conan179** [comment]
Ok, I understood "Reinstall the normal gearsplugin for now" to install the original apk, i.e. without patches.
